# Generated by Django 3.2.9 on 2021-12-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unvetted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_address', models.CharField(max_length=120)),
                ('telegram_url', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
