# Generated by Django 3.2.9 on 2021-12-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_unvetted_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('company_name', models.CharField(max_length=100)),
                ('interest', models.CharField(max_length=200)),
                ('budget', models.CharField(max_length=100)),
                ('proof_of_payment', models.ImageField(upload_to='')),
                ('about_project', models.TextField()),
            ],
        ),
    ]
