# Generated by Django 3.2.9 on 2021-12-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_banner_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='proof_of_payment',
            field=models.CharField(max_length=100),
        ),
    ]
