# Generated by Django 3.2.9 on 2021-12-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_banner_proof_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='unvetted',
            name='proof_of_payment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
