# Generated by Django 3.2.9 on 2021-12-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_unvetted_proof_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='unvetted',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
