# Generated by Django 3.2.9 on 2021-12-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_unvetted_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unvetted',
            name='proof_of_payment',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
