# Generated by Django 3.2.9 on 2021-12-07 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_unvetted_proof_of_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unvetted',
            name='proof_of_payment',
        ),
    ]
